import './globals.css'
import { Jost } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const jost = Jost({
  subsets: ['latin'],     // ✅ REQUIRED to prevent preload error
  preload: true,          // ✅ optional, but usually true by default
  variable: '--font-jost' // ✅ optional, only needed if using Tailwind with font variables
})

export const metadata = {
  title: 'Serendib Resort',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jost.variable}> {/* 👈 this line uses the font variable */}
      <body className="font-sans">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}


